<?php
/**
 * @file
 *
 * Qualtrics field module.
 */

/**
 * Implements hook_help().
 */
function qualtricsxm_embed_help() {

}

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function qualtricsxm_embed_field_info() {
  return array(
    // We name our field as the associative name of the array.
    'field_qualtricsxm_survey' => array(
      'label' => t('QualtricsXM Survey Embed Field'),
      'description' => t('Allows to embed a survey from a remote Qualtrics server.'),
      'default_widget' => 'field_qualtricsxm_dropdown',
      'default_formatter' => 'field_qualtricsxm_iframe',
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 */
function qualtricsxm_embed_field_is_empty($item, $field) {
  return empty($item['sid']);
}

/**
 * Implements hook_field_formatter_info().
 */
function qualtricsxm_embed_field_formatter_info() {
  return array(
    // This formatter just displays the hex value in the color indicated.
    'field_qualtricsxm_iframe' => array(
      'label' => t('QualtricsXM iframe-embedding'),
      'field types' => array('field_qualtricsxm_survey'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function qualtricsxm_embed_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array($items);

  switch ($display['type']) {
    // This formatter adds css to the page changing the '.region-content' area's
    // background color. If there are many fields, the last one will win.
    case 'field_qualtricsxm_iframe':
      foreach ($items as $delta => $item) {
        $theme_vars = array(
          'survey' => array('survey_id' => $item['sid']),
          'width' => $field['settings']['custom']['qualtricsxm_embed_width'],
          'height' => $field['settings']['custom']['qualtricsxm_embed_height'],
          'enable_iframe_resize' => $field['settings']['auto']['qualtricsxm_embed_enable_iframe_auto_resize'],
        );
        $element[$delta] = array(
          '#markup' => theme('qualtricsxm_embed_survey', $theme_vars),
        );
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_field_widget_info().
 */
function qualtricsxm_embed_field_widget_info() {
  return array(
    'field_qualtricsxm_dropdown' => array(
      'label' => t('QualtricsXM Survey Dropdown'),
      'field types' => array('field_qualtricsxm_survey'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function qualtricsxm_embed_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $value = isset($items[$delta]['sid']) ? $items[$delta]['sid'] : '';

  $widget = $element;
  $widget['#delta'] = $delta;
  $widget_options = array();

  $surveys = qualtricsxm_get_surveys();

  if (!empty($surveys)) {
    foreach ($surveys as $survey_id => $survey_info) {
      $widget_options[$survey_id] = $survey_info['surveyname'];
    }
  }
  switch ($instance['widget']['type']) {
    case 'field_qualtricsxm_dropdown':
      $widget += array(
        '#type' => 'select',
        '#default_value' => $value,
        '#options' => $widget_options,
      );
      break;
  }

  $element['sid'] = $widget;
  return $element;
}

/**
 * Implements hook_field_settings_form().
 */
function qualtricsxm_embed_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];

  $form['auto'] = array(
    '#type' => 'fieldset',
    '#title' => t('Auto resize iframe'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['auto']['qualtricsxm_embed_enable_iframe_auto_resize'] = array(
    '#type' => 'checkbox',
    '#title' => t('Iframe auto resize'),
    '#default_value' => isset($settings['auto']['qualtricsxm_embed_enable_iframe_auto_resize']) ? $settings['auto']['qualtricsxm_embed_enable_iframe_auto_resize'] : FALSE,
    '#description' => t("To ensure the auto-resize iframe working, please copy the following code into Qualtrics form header. Untick this if custom iframe Width and Height have been given."),
  );

  $form['auto']['qualtricsxm_embed_cross_region_js'] = array(
    '#type' => 'textarea',

    '#default_value' => '<script> /*Use the "script" opening and closing tags only if you are placing this script in the header of your survey(to run on all pages)*/

   Qualtrics.SurveyEngine.addOnload(function()

   {

       // Wait half a second and then adjust the iframe height to fit the questions

               setTimeout(function () {

                  parent.postMessage( document.getElementById("Wrapper").scrollHeight+"px", "' . $GLOBALS['base_url'] . '");

                                                }, 500);
   });

</script>',

  );

  $form['custom'] = array(
    '#type' => 'fieldset',
    '#title' => t('Custom'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['custom']['qualtricsxm_embed_width'] = array(
    '#type' => 'textfield',
    '#title' => t('Survey iframe width'),
    '#default_value' => isset($settings['custom']['qualtricsxm_embed_width']) ? $settings['custom']['qualtricsxm_embed_width'] : NULL,
    '#element_validate' => array('element_validate_integer_positive'),
    '#description' => t('The width for the iframe. Leave it empty if Auto Resize Iframe has been enabled.'),
  );
  $form['custom']['qualtricsxm_embed_height'] = array(
    '#type' => 'textfield',
    '#title' => t('Survey iframe height'),
    '#default_value' => isset($settings['custom']['qualtricsxm_embed_height']) ? $settings['custom']['qualtricsxm_embed_height'] : NULL,
    '#element_validate' => array('element_validate_integer_positive'),
    '#description' => t('The height for the iframe. Leave it empty if Auto Resize Iframe has been enabled'),
  );
  return $form;
}