<?php

use \Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * Qualtrics field module.
 */

/**
 * Implements hook_help().
 */
function qualtricsxm_embed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    case "help.page.qualtricsxm_embed":
      return '' . t("The Qualtricsxm Embed module provides a renderable field to a Qualtrics form.") . '';
    break;
  }
}
