<?php

/**
 * @file
 * Qualtrics field schema.
 */

/**
 * Implements hook_field_schema().
 */
//function qualtricsxm_embed_field_schema($field) {
//  $columns = array(
//    'sid' => array('type' => 'varchar', 'length' => 50, 'not null' => FALSE),
//  );
//  $indexes = array(
//    'sid' => array('sid'),
//  );
//  return array(
//    'columns' => $columns,
//    'indexes' => $indexes,
//  );
//}
